### ISSUE TITLE
Create a restaurant site

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/restaurant-template#1]
We're going to target specific industries to sell to. This one is restaurants!

Please draw inspiration from wherever you need in order to create a site using Bootstrap for local restaurants.

Some essential items/sections for this template:
menu
hours
location/contact

Some suggestions for inspiration: 
http://www.masuos.biz/
http://www.mercadofoods.com/
http://www.redfactory.nl/themes/therestaurant/menu-card/

due date:
8-4-15 3p

**Comment by jperez4509** [comment]
Done. I have completed the restaurant template.
